version: '3.7'

services:
  maven:
    build: maven/
    volumes:
      - tomcat_webapps:/artifact_folder:rw

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: dbrootpassword
      MYSQL_PASSWORD: dbpassword
      MYSQL_USER: webappuser
      MYSQL_DATABASE: webappdb

  tomcat:
    image: tomcat:9.0.19-jre8-alpine
    volumes:
      - tomcat_webapps:/usr/local/tomcat/webapps:rw
    ports: 
      - "8080:8080"
    depends_on:
      - maven
      - db

volumes:
  tomcat_webapps: