version: '3.8'

services:
  maven:
    build: maven/
    volumes:
      - tomcat_webapps:/artifact_folder:rw

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'dbpassword'
      POSTGRES_USER: 'webappuser'
      POSTGRES_DB: 'webappdb'
    networks:
      - app

  tomcat:
    image: tomcat:9.0.19-jre8-alpine
    volumes:
      - tomcat_webapps:/usr/local/tomcat/webapps:rw
    ports: 
      - "8080:8080"
    links:
      - db
    depends_on:
      - maven
      - db
    command: >
      bash -c "cd /usr/local/tomcat/webapps/
      && ln -s $PWD/App42PaaS-Java-MySQL-Sample-0.0.1-SNAPSHOT $PWD/hwk12
      && cd /var/lib/tomcat9/webapps/ROOT/
      && app42.paas.db.username = "webappuser" >> Config.properties
      && app42.paas.db.port = "5432" >> Config.properties
      && app42.paas.db.password = "dbpassword" >> Config.properties
      && app42.paas.db.ip = "db" >> Config.properties
      && app42.paas.db.name = "webappdb" >> Config.properties"
    networks:
      - app

volumes:
  tomcat_webapps: