version: '3.7'

services:
  maven:
    build: maven/
    volumes:
      - tomcat_webapps:/artifact_folder:rw
      - tomcat_root:/tomcat_root:rw

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'dbrootpassword'
      MYSQL_PASSWORD: 'dbpassword'
      MYSQL_USER: 'webappuser'
      MYSQL_DATABASE: 'webappdb'
    ports: 
      - "3306:3306"

  tomcat:
    build: tomcat/
    volumes:
      - tomcat_webapps:/usr/local/tomcat/webapps:rw
      - tomcat_root:/usr/local/tomcat/webapps/ROOT:rw
    ports: 
      - "8080:8080"
    depends_on:
      - maven
      - db

volumes:
  tomcat_webapps:
  tomcat_root: