version: '3.7'

services:
  maven:
    build: maven/
    volumes:
      - tomcat_webapps:/artifact_folder:rw
      - tomcat_root:/tomcat_root:rw
      - ./test1-host:/test1:rw

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 'dbpassword'
      POSTGRES_USER: 'webappuser'
      POSTGRES_DB: 'webappdb'

  tomcat:
    build: tomcat/
    volumes:
      - tomcat_webapps:/usr/local/tomcat/webapps:rw
      - tomcat_root:/usr/local/tomcat/webapps/ROOT:rw
      - ./test2-host:/test2
    ports: 
      - "8080:8080"
    depends_on:
      - maven
      - db

volumes:
  tomcat_webapps:
  tomcat_root: