version: '3.7'

services:
  maven:
    build:
      context: maven/
    volumes:
      - tomcat_webapps:/artifact_folder:rw

  db:
    image: mariadb:10.5
    restart: always
    volumes:
    - mysql_folder:/var/lib/mysql
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dbrootpassword
      MYSQL_PASSWORD: dbpassword
      MYSQL_USER: webappuser
      MYSQL_DATABASE: webappdb

  tomcat:
    image: tomcat:9-jdk11
    volumes:
      - tomcat_webapps:/usr/local/tomcat/webapps:rw
      - ./config/Config.properties:/usr/local/tomcat/webapps/App42PaaS-Java-MySQL-Sample-0.0.1-SNAPSHOT
    ports: 
      - "8080:8080"
    depends_on:
      - maven
      - db

volumes:
  tomcat_webapps:
  mysql_folder: