version: '3.7'

services:
  maven:
    build: maven/
    volumes:
      - tomcat_webapps:/artifact_folder:rw

  db:
    image: postgres:latest
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'dbpassword'
      POSTGRES_USER: 'webappuser'
      POSTGRES_DB: 'webappdb'

  tomcat:
    build: tomcat/
    volumes:
      - tomcat_webapps:/usr/local/tomcat/webapps:rw
    ports: 
      - "8080:8080"
    depends_on:
      - maven
      - db

volumes:
  tomcat_webapps: